name: build

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'nibbler-nuc'
            path: 'nixosConfigurations."nibbler-nuc".config.system.build.toplevel'
            os: ubuntu-24.04
          - name: 'julian@nibbler-nuc'
            path: 'homeConfigurations."julian@nibbler-nuc".activationPackage'
            os: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19

      # - name: Check flake
      #   run: nix flake check

      - name: Build ${{ matrix.name }}
        run: nix build ".#${{ matrix.path }}"
